# Generated by Django 4.1.1 on 2022-09-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(default='', max_length=25)),
            ],
            options={
                'db_table': 'user_tb',
            },
        ),
    ]
