# Generated by Django 4.0.1 on 2022-09-28 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localadmin', '0003_alter_movies_movie_trailor'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_name', models.CharField(max_length=100)),
                ('Booking_date', models.CharField(max_length=120)),
                ('Booking_time', models.CharField(max_length=20)),
                ('Seat_category', models.CharField(max_length=20)),
                ('Totel_seats', models.IntegerField()),
                ('Selected_seats', models.CharField(max_length=100)),
                ('Totel_amount', models.IntegerField()),
                ('Payment_status', models.CharField(max_length=20)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('Movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localadmin.movies')),
            ],
            options={
                'db_table': 'booking_tb',
            },
        ),
    ]
