# Generated by Django 4.0.1 on 2022-09-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localadmin', '0002_alter_movies_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Movie_trailor',
            field=models.URLField(),
        ),
    ]
